branch-defaults:
  default:
    environment: backend
environment-defaults:
  backend:
    branch: null
    repository: null
    global:
      application_name: conchayoro
      default_ec2_keyname: vockey
      default_platform: Docker
      default_region: us-east-1
      include_git_submodules: true
      instance_profile: LabInstanceProfile
      platform_name: null
      platform_version: null
      profile: null
      sc: null
      workspace_type: Application
      aws:autoscaling:launchconfiguration:
        instance_type: t2.micro
      aws:elasticbeanstalk:application:environment:
        PARAM1: value1
        PARAM2: value2
      aws:elasticbeanstalk:environment:process:bytype:
        WebWorker: 1
